# OpenML Tuning

OpenML 9개 태스크에서 AutoGluon GPU 설정의 실제 성능을 직접 측정하고 정리하는 단일 노트북입니다.

이 노트북에서 바로 하는 일:
- `gpu_default` 설정으로 AutoGluon 성능 측정
- 다른 모델과 비교할 기준 결과 정리
- 실행 중 발생한 문제와 해결 방법 정리
- 한글 요약 문구 자동 생성

고정 조건:
- Kaggle T4
- `time_limit=600`
- `train 80% / test 20%`
- AutoGluon Tabular `1.5.x`
- 기본 GPU 수 `1`

주의:
- 이번 결과는 holdout 실험이므로 OpenML 공식 fold 및 논문 점수와 1:1 비교용은 아닙니다.
- AutoGluon Tabular는 GPU 모델과 CPU 모델이 섞여 돌아갈 수 있습니다.

## 1. Runtime Check

이 구간은 실험 환경을 확인하는 단계입니다.

확인하는 내용:
- Kaggle 런타임인지
- GPU가 잡혔는지
- 결과 저장 디렉터리와 OpenML 캐시 위치가 어디인지

In [12]:
from pathlib import Path
import platform
import subprocess
import sys
import warnings

warnings.filterwarnings('ignore')

print('Python:', sys.version)
subprocess.run(['bash', '-lc', 'nvidia-smi -L || true'], check=False)

IS_KAGGLE = Path('/kaggle').exists()
WORK_DIR = Path('/kaggle/working') if IS_KAGGLE else Path.cwd()
RESULTS_DIR = WORK_DIR / 'autogluon_openml_results'
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
OPENML_CACHE_DIR = WORK_DIR / 'openml_cache'
OPENML_CACHE_DIR.mkdir(parents=True, exist_ok=True)

print('Platform:', platform.platform())
print('IS_KAGGLE:', IS_KAGGLE)
print('WORK_DIR:', WORK_DIR)
print('RESULTS_DIR:', RESULTS_DIR)
print('OPENML_CACHE_DIR:', OPENML_CACHE_DIR)

Python: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
GPU 0: Tesla T4 (UUID: GPU-04a948a2-d4ae-717a-81e4-b67e63c379a5)
GPU 1: Tesla T4 (UUID: GPU-ec5f1f8d-dfbf-4143-cbb1-239d4627b51c)
Platform: Linux-6.6.113+-x86_64-with-glibc2.35
IS_KAGGLE: True
WORK_DIR: /kaggle/working
RESULTS_DIR: /kaggle/working/autogluon_openml_results
OPENML_CACHE_DIR: /kaggle/working/openml_cache

## 2. Package Setup

이 구간은 Kaggle 기본 환경에 필요한 패키지를 맞추는 단계입니다.

구성:
- `autogluon.tabular`, `openml`, `pandas`만 설치해서 실험 흐름을 최대한 단순하게 유지합니다.
- 벤치마크 프레임워크 전체를 설치하는 대신, 실제 실험에 필요한 최소 구성만 사용합니다.

In [13]:
import subprocess
import sys

def run_cmd(args):
    print('$', ' '.join(args))
    subprocess.run(args, check=True)

run_cmd([sys.executable, '-m', 'pip', 'install', '--upgrade', 'pip', 'setuptools', 'wheel'])
run_cmd([
    sys.executable,
    '-m',
    'pip',
    'install',
    'autogluon.tabular[all]>=1.5,<1.6',
    'openml',
    'pandas',
])

print('Install complete.')

$ /usr/bin/python3 -m pip install --upgrade pip setuptools wheel
Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (26.0.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (82.0.1)
Requirement already satisfied: wheel in /usr/local/lib/python3.12/dist-packages (0.46.3)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from wheel) (26.0)
$ /usr/bin/python3 -m pip install autogluon.tabular[all]>=1.5,<1.6 openml pandas
Requirement already satisfied: autogluon.tabular<1.6,>=1.5 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]<1.6,>=1.5) (1.5.0)
Requirement already satisfied: openml in /usr/local/lib/python3.12/dist-packages (0.15.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.3.3)
Requirement already satisfied: numpy<2.4.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (2.0.2)
Requirement already satisfied: scipy<1.17,>=1.5.4 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (1.16.3)
Requirement already satisfied: scikit-learn<1.8.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (1.6.1)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (3.6.1)
Requirement already satisfied: autogluon.core==1.5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (1.5.0)
Requirement already satisfied: autogluon.features==1.5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (1.5.0)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (2.32.4)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (3.10.0)
Requirement already satisfied: boto3<2,>=1.10 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (1.42.70)
Requirement already satisfied: autogluon.common==1.5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (1.5.0)
Requirement already satisfied: pyarrow<21.0.0,>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (20.0.0)
Requirement already satisfied: psutil<7.2.0,>=5.7.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (5.9.5)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (1.5.3)
Requirement already satisfied: pyyaml>=5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: einx in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]<1.6,>=1.5) (0.4.3)
Requirement already satisfied: lightgbm<4.7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]<1.6,>=1.5) (4.6.0)
Requirement already satisfied: torch<2.10,>=2.6 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]<1.6,>=1.5) (2.9.1)
Requirement already satisfied: huggingface_hub<1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (0.36.2)
Requirement already satisfied: omegaconf in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]<1.6,>=1.5) (2.3.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]<1.6,>=1.5) (4.57.6)
Requirement already satisfied: xgboost<3.2,>=2.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]<1.6,>=1.5) (3.1.3)
Requirement already satisfied: catboost<1.3,>=1.2 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]<1.6,>=1.5) (1.2.10)
Requirement already satisfied: fastai<2.9,>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]<1.6,>=1.5) (2.8.7)
Requirement already satisfied: loguru in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]<1.6,>=1.5) (0.7.3)
Requirement already satisfied: einops<0.9,>=0.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]<1.6,>=1.5) (0.8.2)
Requirement already satisfied: spacy<3.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]<1.6,>=1.5) (3.8.11)
Requirement already satisfied: ray<2.53,>=2.43.0 in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (2.52.1)
Requirement already satisfied: hyperopt<0.2.8,>=0.2.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (0.2.7)
Requirement already satisfied: stevedore<5.5 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (5.4.1)
Requirement already satisfied: botocore<1.43.0,>=1.42.70 in /usr/local/lib/python3.12/dist-packages (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (1.42.70)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (0.16.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<1.43.0,>=1.42.70->boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (2.5.0)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]<1.6,>=1.5) (0.21)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]<1.6,>=1.5) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]<1.6,>=1.5) (1.17.0)
Requirement already satisfied: fastdownload<2,>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]<1.6,>=1.5) (0.0.7)
Requirement already satisfied: fastcore>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]<1.6,>=1.5) (1.12.16)
Requirement already satisfied: fasttransform>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]<1.6,>=1.5) (0.0.2)
Requirement already satisfied: torchvision>=0.11 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]<1.6,>=1.5) (0.24.1)
Requirement already satisfied: fastprogress>=0.2.4 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]<1.6,>=1.5) (1.1.5)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]<1.6,>=1.5) (11.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]<1.6,>=1.5) (26.0)
Requirement already satisfied: plum-dispatch in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]<1.6,>=1.5) (2.7.1)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]<1.6,>=1.5) (3.1.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (1.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (4.15.0)
Requirement already satisfied: safetensors[torch] in /usr/local/lib/python3.12/dist-packages (from huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (0.7.0)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (1.0.0)
Requirement already satisfied: py4j in /usr/local/lib/python3.12/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (0.10.9.9)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (3.3.2)
Requirement already satisfied: click!=8.3.*,>=7.0 in /usr/local/lib/python3.12/dist-packages (from ray<2.53,>=2.43.0->ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (8.2.1)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.12/dist-packages (from ray<2.53,>=2.43.0->ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (4.26.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ray<2.53,>=2.43.0->ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (1.1.2)
Requirement already satisfied: protobuf>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from ray<2.53,>=2.43.0->ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (5.29.5)
Requirement already satisfied: aiohttp>=3.7 in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (3.13.3)
Requirement already satisfied: aiohttp_cors in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (0.8.1)
Requirement already satisfied: colorful in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (0.5.8)
Requirement already satisfied: py-spy>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (0.4.1)
Requirement already satisfied: grpcio>=1.42.0 in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (1.78.1)
Requirement already satisfied: opencensus in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (0.11.4)
Requirement already satisfied: opentelemetry-sdk>=1.30.0 in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (1.38.0)
Requirement already satisfied: opentelemetry-exporter-prometheus in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (0.59b0)
Requirement already satisfied: opentelemetry-proto in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (1.38.0)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3 in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (2.12.3)
Requirement already satisfied: prometheus_client>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (0.24.1)
Requirement already satisfied: smart_open in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (7.5.1)
Requirement already satisfied: virtualenv!=20.21.1,>=20.0.24 in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (21.2.4)
Requirement already satisfied: tensorboardX>=1.9 in /usr/local/lib/python3.12/dist-packages (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (2.6.5)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3->ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3->ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3->ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0; extra == "all"->autogluon.tabular[all]<1.6,>=1.5) (0.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<1.8.0,>=1.4.0->autogluon.tabular<1.6,>=1.5->autogluon.tabular[all]<1.6,>=1.5) (3.6.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9->autogluon.tabular[all]<1.6,>=1.5) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9->autogluon.tabular[all]<1.6,>=1.5) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9->autogluon.tabular[all]<1.6,>=1.5) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9->autogluon.tabular[all]<1.6,>=1.5) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9->autogluon.tabular[all]<1.6,>=1.5) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9->autogluon.tabular[all]<1.6,>=1.5) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9->autogluon.tabular[all]<1.6,>=1.5) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9->autogluon.tabular[all]<1.6,>=1.5) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9->autogluon.tabular[all]<1.6,>=1.5) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9->autogluon.tabular[all]<1.6,>=1.5) (0.4.3)

## 3. Experiment Design

여기서는 비교할 실험 조건을 고정합니다.

핵심 설정:
- OpenML 9개 태스크만 사용
- `time_limit=600`, `train_ratio=0.8`, `split_seed=42`
- 실험 설정: `gpu_default`

설정 의미:
- `gpu_default`: AutoGluon 기본 탐색 공간을 유지하면서 GPU만 켠 대표 설정
- 다른 모델과 비교할 때 AutoGluon 쪽 기준 결과로 사용

In [14]:
import json
import pandas as pd

TASKS = [
    {'task_order': 10, 'name': 'guillermo', 'openml_id': 168337, 'metric': 'roc_auc'},
    {'task_order': 11, 'name': 'riccardo', 'openml_id': 168338, 'metric': 'roc_auc'},
    {'task_order': 12, 'name': 'amazon_employee', 'openml_id': 34539, 'metric': 'roc_auc'},
    {'task_order': 13, 'name': 'nomao', 'openml_id': 9977, 'metric': 'roc_auc'},
    {'task_order': 14, 'name': 'bank-marketing', 'openml_id': 14965, 'metric': 'roc_auc'},
    {'task_order': 15, 'name': 'adult', 'openml_id': 7592, 'metric': 'roc_auc'},
    {'task_order': 16, 'name': 'kddcup09_appetency', 'openml_id': 3945, 'metric': 'roc_auc'},
    {'task_order': 17, 'name': 'apsfailure', 'openml_id': 168868, 'metric': 'roc_auc'},
    {'task_order': 18, 'name': 'numerai28.6', 'openml_id': 167120, 'metric': 'roc_auc'},
]

EXPERIMENT_NAME = 'openml_gpu_default'
TIME_LIMIT = 600
TRAIN_RATIO = 0.8
SPLIT_SEED = 42
VERBOSITY = 2
NUM_GPUS = 1
MAX_TASKS = None
RESUME = True
DRY_RUN = False

RECIPE_LIBRARY = {
    'gpu_default': {
        'description': 'GPU enabled, default search space',
        'num_gpus': NUM_GPUS,
        'presets': None,
    },
}
ACTIVE_RECIPE_NAMES = ['gpu_default']
BASELINE_RECIPE_NAME = None

selected_tasks = TASKS[:MAX_TASKS] if MAX_TASKS else TASKS
active_recipes = []
for recipe_name in ACTIVE_RECIPE_NAMES:
    recipe_cfg = RECIPE_LIBRARY[recipe_name].copy()
    recipe_cfg['recipe_name'] = recipe_name
    active_recipes.append(recipe_cfg)

RESULTS_CSV = RESULTS_DIR / f'{EXPERIMENT_NAME}_results.csv'
RUN_CONFIG_PATH = RESULTS_DIR / f'{EXPERIMENT_NAME}_config.json'

existing_results = pd.DataFrame()
completed_keys = set()
if RESUME and RESULTS_CSV.exists():
    existing_results = pd.read_csv(RESULTS_CSV)
    required_cols = {'dataset', 'recipe_name'}
    if required_cols.issubset(existing_results.columns):
        completed_keys = set(zip(existing_results['dataset'].astype(str), existing_results['recipe_name'].astype(str)))

run_config = {
    'experiment_name': EXPERIMENT_NAME,
    'tasks': selected_tasks,
    'active_recipe_names': ACTIVE_RECIPE_NAMES,
    'time_limit': TIME_LIMIT,
    'train_ratio': TRAIN_RATIO,
    'split_seed': SPLIT_SEED,
    'num_gpus': NUM_GPUS,
    'results_csv': str(RESULTS_CSV),
}
RUN_CONFIG_PATH.write_text(json.dumps(run_config, ensure_ascii=False, indent=2), encoding='utf-8')

print('selected task count:', len(selected_tasks))
print('selected task names:', [task['name'] for task in selected_tasks])
print('ACTIVE_RECIPE_NAMES:', ACTIVE_RECIPE_NAMES)
print('TIME_LIMIT:', TIME_LIMIT)
print('TRAIN_RATIO:', TRAIN_RATIO)
print('NUM_GPUS:', NUM_GPUS)
print('RESULTS_CSV:', RESULTS_CSV)
print('RUN_CONFIG_PATH:', RUN_CONFIG_PATH)
print('already completed:', len(completed_keys))

pd.DataFrame(selected_tasks)

selected task count: 9
selected task names: ['guillermo', 'riccardo', 'amazon_employee', 'nomao', 'bank-marketing', 'adult', 'kddcup09_appetency', 'apsfailure', 'numerai28.6']
ACTIVE_RECIPE_NAMES: ['gpu_default']
TIME_LIMIT: 600
TRAIN_RATIO: 0.8
NUM_GPUS: 1
RESULTS_CSV: /kaggle/working/autogluon_openml_results/openml_gpu_default_results.csv
RUN_CONFIG_PATH: /kaggle/working/autogluon_openml_results/openml_gpu_default_config.json
already completed: 0

   task_order                name  openml_id   metric
0          10           guillermo     168337  roc_auc
1          11            riccardo     168338  roc_auc
2          12     amazon_employee      34539  roc_auc
3          13               nomao       9977  roc_auc
4          14      bank-marketing      14965  roc_auc
5          15               adult       7592  roc_auc
6          16  kddcup09_appetency       3945  roc_auc
7          17          apsfailure     168868  roc_auc
8          18         numerai28.6     167120  roc_auc

## 4. Helper Functions

이 구간은 실험을 반복 가능하게 만드는 공통 함수들입니다.

포함된 역할:
- OpenML 데이터셋 다운로드 및 로드
- `80:20` stratified holdout 분할
- AutoGluon 입력 형태로 데이터 변환
- AutoGluon 학습 설정 구성
- ROC AUC 계산 및 단일 task 실행 함수 정의

In [15]:
import shutil
import tempfile
import time

import openml
import pandas as pd
from autogluon.tabular import TabularPredictor
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

openml.config.cache_directory = str(OPENML_CACHE_DIR)

def load_task_dataset(task_id):
    task = openml.tasks.get_task(task_id, download_splits=True)
    dataset = task.get_dataset()
    X, y, _, _ = dataset.get_data(
        dataset_format='dataframe',
        target=dataset.default_target_attribute,
    )
    target_col = dataset.default_target_attribute
    if not isinstance(y, pd.Series):
        y = pd.Series(y, name=target_col)
    return X.copy(), y.copy(), target_col

def split_task_data(task_id, train_ratio, split_seed):
    X, y, target_col = load_task_dataset(task_id)
    label_counts = y.value_counts(dropna=False)
    stratify = y if len(label_counts) > 1 and int(label_counts.min()) >= 2 else None
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        train_size=train_ratio,
        random_state=split_seed,
        shuffle=True,
        stratify=stratify,
    )
    return X_train.copy(), X_test.copy(), y_train.copy(), y_test.copy(), target_col

def make_df(X, y, target_col):
    df = X.copy()
    df[target_col] = y.to_numpy()
    return df

def score_task(predictor, X_test, y_test):
    y_proba = predictor.predict_proba(X_test)
    if isinstance(y_proba, pd.DataFrame):
        if y_proba.shape[1] < 2:
            raise ValueError('ROC AUC scoring requires binary probability columns.')
        positive_proba = y_proba.iloc[:, 1]
    else:
        positive_proba = y_proba
    return float(roc_auc_score(y_test, positive_proba))

def run_single_experiment(task_cfg, recipe_cfg):
    task_name = task_cfg['name']
    recipe_name = recipe_cfg['recipe_name']
    model_dir = Path(tempfile.mkdtemp(prefix=f'{task_name}_{recipe_name}_', dir=str(WORK_DIR)))
    started = time.time()

    row = {
        'task_order': task_cfg['task_order'],
        'dataset': task_name,
        'openml_id': task_cfg['openml_id'],
        'metric': task_cfg['metric'],
        'recipe_name': recipe_name,
        'score': None,
        'train_sec': None,
        'best_model': None,
        'trained_models': None,
        'status': 'error',
        'error': None,
    }

    try:
        X_train, X_test, y_train, y_test, target_col = split_task_data(
            task_cfg['openml_id'],
            train_ratio=TRAIN_RATIO,
            split_seed=SPLIT_SEED,
        )
        train_df = make_df(X_train, y_train, target_col)

        predictor = TabularPredictor(
            label=target_col,
            eval_metric=task_cfg['metric'],
            path=str(model_dir),
            verbosity=VERBOSITY,
        )

        fit_kwargs = {
            'train_data': train_df,
            'time_limit': TIME_LIMIT,
            'num_gpus': recipe_cfg['num_gpus'],
        }
        if recipe_cfg['presets'] is not None:
            fit_kwargs['presets'] = recipe_cfg['presets']

        predictor.fit(**fit_kwargs)
        leaderboard = predictor.leaderboard(silent=True)

        row['score'] = score_task(predictor, X_test, y_test)
        row['train_sec'] = round(time.time() - started, 2)
        row['best_model'] = predictor.model_best
        row['trained_models'] = int(len(leaderboard))
        row['status'] = 'ok'
        return row
    except Exception as exc:
        row['train_sec'] = round(time.time() - started, 2)
        row['error'] = str(exc)
        return row
    finally:
        shutil.rmtree(model_dir, ignore_errors=True)

## 5. Run Benchmark

이 구간은 태스크와 recipe를 순차적으로 돌리면서 결과를 누적 저장하는 실행 셀입니다.

실행 방식:
- 각 데이터셋에 대해 `gpu_default` 설정으로 실행
- 매 실행마다 결과를 CSV에 저장
- 이미 끝난 조합은 `RESUME=True`일 때 자동으로 건너뜀

In [16]:
import pandas as pd
import time

run_rows = []
if not existing_results.empty:
    run_rows.extend(existing_results.to_dict(orient='records'))

if DRY_RUN:
    print('DRY_RUN=True 이므로 실제 실행은 건너뜁니다.')
else:
    session_start = time.time()
    total_runs = len(selected_tasks) * len(active_recipes)
    current_run = 0

    for task_cfg in selected_tasks:
        for recipe_cfg in active_recipes:
            current_run += 1
            run_key = (task_cfg['name'], recipe_cfg['recipe_name'])
            if run_key in completed_keys:
                print(f"[{current_run}/{total_runs}] skip: {task_cfg['name']} / {recipe_cfg['recipe_name']} (already completed)")
                continue

            elapsed_min = (time.time() - session_start) / 60
            print(f"\n[{current_run}/{total_runs}] elapsed={elapsed_min:.1f} min")
            row = run_single_experiment(task_cfg, recipe_cfg)
            print({k: row[k] for k in ['dataset', 'recipe_name', 'score', 'train_sec', 'status', 'error']})
            run_rows.append(row)
            completed_keys.add(run_key)
            pd.DataFrame(run_rows).sort_values(['task_order', 'recipe_name']).to_csv(RESULTS_CSV, index=False)

    print(f"\nDone. Total elapsed: {(time.time() - session_start) / 60:.1f} min")

run_df = pd.DataFrame(run_rows)
if not run_df.empty:
    run_df = run_df.sort_values(['task_order', 'recipe_name']).reset_index(drop=True)

print('saved to:', RESULTS_CSV)
print('rows:', len(run_df))
run_df.tail()

[1/9] elapsed=0.0 min

Warning: path already exists! This predictor may overwrite an existing predictor! path="/kaggle/working/guillermo_gpu_default_m9rf9mzs"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Sat Jan 17 11:20:45 UTC 2026
CPU Count:          4
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 14.54/14.56 GB | GPU 1: 14.56/14.56 GB
Total GPU Memory:   Free: 29.10 GB, Allocated: 0.03 GB, Total: 29.13 GB
GPU Count:          2
Memory Avail:       18.29 GB / 31.35 GB (58.3%)
Disk Space Avail:   19.50 GB / 19.52 GB (99.9%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/kaggle/working/guillermo_gpu_default_m9rf9mzs"
Train Data Rows:    16000
Train Data Columns: 4296
Label Column:       class
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['0', '1']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (1) vs negative (0) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    18714.89 MB
	Train Data (Original)  Memory Usage: 522.81 MB (2.8% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 15): ['V392', 'V1270', 'V1346', 'V2185', 'V2288', 'V2311', 'V2394', 'V2802', 'V2824', 'V2891', 'V3031', 'V3201', 'V3333', 'V3884', 'V4060']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 4281 | ['V1', 'V2', 'V3', 'V4', 'V5', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 4280 | ['V1', 'V2', 'V3', 'V4', 'V5', ...]
		('int', ['bool']) :    1 | ['V777']
	10.4s = Fit runtime
	4281 features in original data used to generate 4281 features in processed data.
	Train Data (Processed) Memory Usage: 522.48 MB (2.8% of available memory)
Data preprocessing and feature engineering runtime = 11.97s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 14400, Val Rows: 1600
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 588.03s of the 588.03s of remaining time.
	Fitting with cpus=2, gpus=1, mem=3.3/17.3 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.

[1000]	valid_set's binary_logloss: 0.415974

	0.8819	 = Validation score   (roc_auc)
	182.0s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 405.85s of the 405.85s of remaining time.
	Fitting with cpus=2, gpus=1, mem=3.3/17.3 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.8855	 = Validation score   (roc_auc)
	169.55s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 236.18s of the 236.18s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/17.3 GB
	0.8674	 = Validation score   (roc_auc)
	79.25s	 = Training   runtime
	0.14s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 156.73s of the 156.73s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/17.3 GB
	0.8713	 = Validation score   (roc_auc)
	80.63s	 = Training   runtime
	0.14s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 75.90s of the 75.89s of remaining time.
	Fitting with cpus=2, gpus=1, mem=6.6/17.3 GB
	Training CatBoost with GPU, note that this may negatively impact model quality compared to CPU training.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	0.8664	 = Validation score   (roc_auc)
	36.73s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 39.06s of the 39.06s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/17.3 GB
	0.806	 = Validation score   (roc_auc)
	21.72s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 17.08s of the 17.08s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/17.3 GB
	0.82	 = Validation score   (roc_auc)
	21.53s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the -4.71s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=4, gpus=1, mem=0.0/17.3 GB
	Ensemble Weights: {'LightGBM': 0.462, 'LightGBMXT': 0.308, 'RandomForestGini': 0.231}
	0.8875	 = Validation score   (roc_auc)
	0.08s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 605.85s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4683.4 rows/s (1600 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/kaggle/working/guillermo_gpu_default_m9rf9mzs")

{'dataset': 'guillermo', 'recipe_name': 'gpu_default', 'score': 0.9057565886681392, 'train_sec': 611.62, 'status': 'ok', 'error': None}

[2/9] elapsed=10.2 min

Warning: path already exists! This predictor may overwrite an existing predictor! path="/kaggle/working/riccardo_gpu_default_0jtxi9u0"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Sat Jan 17 11:20:45 UTC 2026
CPU Count:          4
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 14.54/14.56 GB | GPU 1: 14.56/14.56 GB
Total GPU Memory:   Free: 29.10 GB, Allocated: 0.03 GB, Total: 29.13 GB
GPU Count:          2
Memory Avail:       18.27 GB / 31.35 GB (58.3%)
Disk Space Avail:   19.50 GB / 19.52 GB (99.9%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/kaggle/working/riccardo_gpu_default_0jtxi9u0"
Train Data Rows:    16000
Train Data Columns: 4296
Label Column:       class
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['0', '1']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (1) vs negative (0) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    18688.99 MB
	Train Data (Original)  Memory Usage: 523.03 MB (2.8% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 13): ['V392', 'V1270', 'V1346', 'V2185', 'V2288', 'V2311', 'V2394', 'V2802', 'V2824', 'V3031', 'V3333', 'V3884', 'V4060']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 4283 | ['V1', 'V2', 'V3', 'V4', 'V5', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 4283 | ['V1', 'V2', 'V3', 'V4', 'V5', ...]
	11.4s = Fit runtime
	4283 features in original data used to generate 4283 features in processed data.
	Train Data (Processed) Memory Usage: 522.83 MB (2.8% of available memory)
Data preprocessing and feature engineering runtime = 12.37s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 14400, Val Rows: 1600
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 587.63s of the 587.63s of remaining time.
	Fitting with cpus=2, gpus=1, mem=3.3/17.3 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.9999	 = Validation score   (roc_auc)
	160.34s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 427.15s of the 427.15s of remaining time.
	Fitting with cpus=2, gpus=1, mem=3.3/17.5 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.9999	 = Validation score   (roc_auc)
	195.64s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 231.38s of the 231.38s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/17.5 GB
	0.9989	 = Validation score   (roc_auc)
	125.14s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 106.05s of the 106.05s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/17.5 GB
	0.9988	 = Validation score   (roc_auc)
	104.5s	 = Training   runtime
	0.14s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1.36s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=4, gpus=1, mem=0.0/17.5 GB
	Ensemble Weights: {'RandomForestGini': 0.75, 'LightGBM': 0.25}
	0.9999	 = Validation score   (roc_auc)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 599.74s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 7169.4 rows/s (1600 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/kaggle/working/riccardo_gpu_default_0jtxi9u0")
Warning: path already exists! This predictor may overwrite an existing predictor! path="/kaggle/working/amazon_employee_gpu_default_gqqqep03"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Sat Jan 17 11:20:45 UTC 2026
CPU Count:          4
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 14.54/14.56 GB | GPU 1: 14.56/14.56 GB
Total GPU Memory:   Free: 29.10 GB, Allocated: 0.03 GB, Total: 29.13 GB
GPU Count:          2
Memory Avail:       19.64 GB / 31.35 GB (62.6%)
Disk Space Avail:   19.50 GB / 19.52 GB (99.9%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'

{'dataset': 'riccardo', 'recipe_name': 'gpu_default', 'score': 0.9997336666666667, 'train_sec': 605.26, 'status': 'ok', 'error': None}

[3/9] elapsed=20.3 min

Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/kaggle/working/amazon_employee_gpu_default_gqqqep03"
Train Data Rows:    26215
Train Data Columns: 9
Label Column:       target
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['1', '0']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (1) vs negative (0) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    20109.41 MB
	Train Data (Original)  Memory Usage: 1.23 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['ROLE_CODE']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('category', []) : 1 | ['ROLE_CODE']
	Types of features in original data (raw dtype, special dtypes):
		('category', []) : 8 | ['RESOURCE', 'MGR_ID', 'ROLE_ROLLUP_1', 'ROLE_ROLLUP_2', 'ROLE_DEPTNAME', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 8 | ['RESOURCE', 'MGR_ID', 'ROLE_ROLLUP_1', 'ROLE_ROLLUP_2', 'ROLE_DEPTNAME', ...]
	0.2s = Fit runtime
	8 features in original data used to generate 8 features in processed data.
	Train Data (Processed) Memory Usage: 0.36 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.21s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0954, Train Rows: 23714, Val Rows: 2501
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 599.79s of the 599.79s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.0/19.6 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
[LightGBM] [Fatal] bin size 2352 cannot run on GPU
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu
	0.8382	 = Validation score   (roc_auc)
	1.71s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 597.97s of the 597.97s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.0/19.6 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
[LightGBM] [Fatal] bin size 2352 cannot run on GPU
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu
	0.8432	 = Validation score   (roc_auc)
	1.23s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 596.71s of the 596.71s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/19.6 GB
	0.8321	 = Validation score   (roc_auc)
	3.22s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 593.30s of the 593.30s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/19.6 GB
	0.8467	 = Validation score   (roc_auc)
	3.44s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 589.65s of the 589.65s of remaining time.
	Fitting with cpus=2, gpus=1
	Training CatBoost with GPU, note that this may negatively impact model quality compared to CPU training.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	0.8826	 = Validation score   (roc_auc)
	30.86s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 558.66s of the 558.65s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/19.6 GB
	0.8368	 = Validation score   (roc_auc)
	1.88s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 556.52s of the 556.52s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/19.6 GB
	0.8264	 = Validation score   (roc_auc)
	1.78s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 554.49s of the 554.49s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.0/19.6 GB
No improvement since epoch 2: early stopping
	0.7853	 = Validation score   (roc_auc)
	19.0s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 535.41s of the 535.41s of remaining time.
	Fitting with cpus=2, gpus=1
	0.8358	 = Validation score   (roc_auc)
	3.54s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 531.81s of the 531.81s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.0/19.6 GB
	0.8258	 = Validation score   (roc_auc)
	24.89s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 506.89s of the 506.89s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.1/19.6 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
[LightGBM] [Fatal] bin size 2352 cannot run on GPU
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu
	0.8457	 = Validation score   (roc_auc)
	1.64s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 505.19s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=4, gpus=1, mem=0.0/19.6 GB
	Ensemble Weights: {'CatBoost': 0.958, 'XGBoost': 0.042}
	0.8827	 = Validation score   (roc_auc)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 94.97s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 35372.8 rows/s (2501 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/kaggle/working/amazon_employee_gpu_default_gqqqep03")
Warning: path already exists! This predictor may overwrite an existing predictor! path="/kaggle/working/nomao_gpu_default_rtwygwz1"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Sat Jan 17 11:20:45 UTC 2026
CPU Count:          4
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 14.54/14.56 GB | GPU 1: 14.56/14.56 GB
Total GPU Memory:   Free: 29.10 GB, Allocated: 0.03 GB, Total: 29.13 GB
GPU Count:          2
Memory Avail:       19.72 GB / 31.35 GB (62.9%)
Disk Space Avail:   19.50 GB / 19.52 GB (99.9%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'

{'dataset': 'amazon_employee', 'recipe_name': 'gpu_default', 'score': 0.8836535523912277, 'train_sec': 96.66, 'status': 'ok', 'error': None}

[4/9] elapsed=21.9 min

Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/kaggle/working/nomao_gpu_default_rtwygwz1"
Train Data Rows:    27572
Train Data Columns: 118
Label Column:       Class
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['2', '1']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 2, class 0 = 1
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (2) vs negative (1) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    20213.77 MB
	Train Data (Original)  Memory Usage: 19.49 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 2 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 8): ['V42', 'V48', 'V82', 'V83', 'V84', 'V85', 'V86', 'V88']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('category', []) : 2 | ['V48', 'V88']
		('float', [])    : 6 | ['V42', 'V82', 'V83', 'V84', 'V85', ...]
	Types of features in original data (raw dtype, special dtypes):
		('category', []) : 27 | ['V7', 'V8', 'V15', 'V16', 'V23', ...]
		('float', [])    : 83 | ['V1', 'V2', 'V3', 'V4', 'V5', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 25 | ['V15', 'V16', 'V23', 'V24', 'V31', ...]
		('float', [])     : 83 | ['V1', 'V2', 'V3', 'V4', 'V5', ...]
		('int', ['bool']) :  2 | ['V7', 'V8']
	0.3s = Fit runtime
	110 features in original data used to generate 110 features in processed data.
	Train Data (Processed) Memory Usage: 18.18 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.38s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0907, Train Rows: 25071, Val Rows: 2501
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 599.62s of the 599.62s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.1/19.7 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.9951	 = Validation score   (roc_auc)
	5.86s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 593.62s of the 593.62s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.1/19.7 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.995	 = Validation score   (roc_auc)
	5.11s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 588.42s of the 588.42s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/19.7 GB
	0.9936	 = Validation score   (roc_auc)
	4.83s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 583.42s of the 583.41s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/19.7 GB
	0.9928	 = Validation score   (roc_auc)
	4.73s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 578.52s of the 578.52s of remaining time.
	Fitting with cpus=2, gpus=1
	Training CatBoost with GPU, note that this may negatively impact model quality compared to CPU training.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	0.9939	 = Validation score   (roc_auc)
	62.07s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 516.40s of the 516.40s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/19.8 GB
	0.9936	 = Validation score   (roc_auc)
	2.75s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 513.45s of the 513.45s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.1/19.8 GB
	0.9936	 = Validation score   (roc_auc)
	2.46s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 510.78s of the 510.78s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.2/19.8 GB
	0.9921	 = Validation score   (roc_auc)
	38.62s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 472.07s of the 472.07s of remaining time.
	Fitting with cpus=2, gpus=1
	0.9942	 = Validation score   (roc_auc)
	2.28s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 469.73s of the 469.73s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.1/19.7 GB
	0.9921	 = Validation score   (roc_auc)
	23.07s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 446.59s of the 446.58s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.2/19.7 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.9948	 = Validation score   (roc_auc)
	9.56s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 436.91s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=4, gpus=1, mem=0.0/19.7 GB
	Ensemble Weights: {'LightGBMXT': 0.474, 'LightGBM': 0.368, 'XGBoost': 0.105, 'RandomForestGini': 0.053}
	0.9955	 = Validation score   (roc_auc)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 163.28s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 8210.7 rows/s (2501 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/kaggle/working/nomao_gpu_default_rtwygwz1")
Warning: path already exists! This predictor may overwrite an existing predictor! path="/kaggle/working/bank-marketing_gpu_default_d40rcgvl"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Sat Jan 17 11:20:45 UTC 2026
CPU Count:          4
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 14.54/14.56 GB | GPU 1: 14.56/14.56 GB
Total GPU Memory:   Free: 29.10 GB, Allocated: 0.03 GB, Total: 29.13 GB
GPU Count:          2
Memory Avail:       19.76 GB / 31.35 GB (63.0%)
Disk Space Avail:   19.50 GB / 19.52 GB (99.9%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'

{'dataset': 'nomao', 'recipe_name': 'gpu_default', 'score': 0.9961906504516181, 'train_sec': 165.55, 'status': 'ok', 'error': None}

[5/9] elapsed=24.7 min

Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/kaggle/working/bank-marketing_gpu_default_d40rcgvl"
Train Data Rows:    36168
Train Data Columns: 16
Label Column:       Class
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['1', '2']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 2, class 0 = 1
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (2) vs negative (1) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    20231.62 MB
	Train Data (Original)  Memory Usage: 1.52 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('category', []) : 9 | ['V2', 'V3', 'V4', 'V5', 'V7', ...]
		('float', [])    : 4 | ['V6', 'V12', 'V14', 'V15']
		('int', [])      : 3 | ['V1', 'V10', 'V13']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 6 | ['V2', 'V3', 'V4', 'V9', 'V11', ...]
		('float', [])     : 4 | ['V6', 'V12', 'V14', 'V15']
		('int', [])       : 3 | ['V1', 'V10', 'V13']
		('int', ['bool']) : 3 | ['V5', 'V7', 'V8']
	0.1s = Fit runtime
	16 features in original data used to generate 16 features in processed data.
	Train Data (Processed) Memory Usage: 1.52 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.15s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0691, Train Rows: 33668, Val Rows: 2500
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 599.85s of the 599.85s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.0/19.8 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.9303	 = Validation score   (roc_auc)
	2.46s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 597.34s of the 597.34s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.0/19.8 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.9278	 = Validation score   (roc_auc)
	2.04s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 595.25s of the 595.25s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/19.8 GB
	0.9248	 = Validation score   (roc_auc)
	5.22s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 589.79s of the 589.79s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/19.8 GB
	0.9254	 = Validation score   (roc_auc)
	5.49s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 584.06s of the 584.06s of remaining time.
	Fitting with cpus=2, gpus=1
	Training CatBoost with GPU, note that this may negatively impact model quality compared to CPU training.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	0.9284	 = Validation score   (roc_auc)
	47.47s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 536.56s of the 536.56s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/19.8 GB
	0.9189	 = Validation score   (roc_auc)
	3.15s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 533.09s of the 533.09s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/19.8 GB
	0.9191	 = Validation score   (roc_auc)
	2.9s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 529.90s of the 529.90s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.0/19.8 GB
No improvement since epoch 9: early stopping
	0.9265	 = Validation score   (roc_auc)
	34.94s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 494.89s of the 494.89s of remaining time.
	Fitting with cpus=2, gpus=1
	0.9293	 = Validation score   (roc_auc)
	0.77s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 494.09s of the 494.09s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.0/19.8 GB
	0.9188	 = Validation score   (roc_auc)
	55.04s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 439.02s of the 439.02s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.1/19.7 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.9278	 = Validation score   (roc_auc)
	4.29s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 434.64s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=4, gpus=1, mem=0.0/19.8 GB
	Ensemble Weights: {'NeuralNetFastAI': 0.32, 'LightGBMXT': 0.2, 'RandomForestGini': 0.2, 'XGBoost': 0.16, 'CatBoost': 0.08, 'RandomForestEntr': 0.04}
	0.9348	 = Validation score   (roc_auc)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 165.52s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 7297.2 rows/s (2500 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/kaggle/working/bank-marketing_gpu_default_d40rcgvl")
Warning: path already exists! This predictor may overwrite an existing predictor! path="/kaggle/working/adult_gpu_default_q4vvg9pk"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Sat Jan 17 11:20:45 UTC 2026
CPU Count:          4
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 14.54/14.56 GB | GPU 1: 14.56/14.56 GB
Total GPU Memory:   Free: 29.10 GB, Allocated: 0.03 GB, Total: 29.13 GB
GPU Count:          2
Memory Avail:       19.77 GB / 31.35 GB (63.1%)
Disk Space Avail:   19.50 GB / 19.52 GB (99.9%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'

{'dataset': 'bank-marketing', 'recipe_name': 'gpu_default', 'score': 0.9369273436843419, 'train_sec': 167.88, 'status': 'ok', 'error': None}

[6/9] elapsed=27.5 min

Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/kaggle/working/adult_gpu_default_q4vvg9pk"
Train Data Rows:    39073
Train Data Columns: 14
Label Column:       class
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['<=50K', '>50K']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = >50K, class 0 = <=50K
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (>50K) vs negative (<=50K) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    20245.02 MB
	Train Data (Original)  Memory Usage: 1.31 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('category', []) : 8 | ['workclass', 'education', 'marital-status', 'occupation', 'relationship', ...]
		('float', [])    : 3 | ['fnlwgt', 'capital-gain', 'capital-loss']
		('int', [])      : 3 | ['age', 'education-num', 'hours-per-week']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 7 | ['workclass', 'education', 'marital-status', 'occupation', 'relationship', ...]
		('float', [])     : 3 | ['fnlwgt', 'capital-gain', 'capital-loss']
		('int', [])       : 3 | ['age', 'education-num', 'hours-per-week']
		('int', ['bool']) : 1 | ['sex']
	0.1s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 1.31 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.14s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.064, Train Rows: 36572, Val Rows: 2501
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 599.86s of the 599.86s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.0/19.8 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.9159	 = Validation score   (roc_auc)
	4.92s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 594.74s of the 594.74s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.0/19.8 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.921	 = Validation score   (roc_auc)
	2.61s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 592.06s of the 592.06s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/19.8 GB
	0.8984	 = Validation score   (roc_auc)
	5.1s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 586.62s of the 586.62s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/19.8 GB
	0.8979	 = Validation score   (roc_auc)
	5.62s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 580.67s of the 580.67s of remaining time.
	Fitting with cpus=2, gpus=1
	Training CatBoost with GPU, note that this may negatively impact model quality compared to CPU training.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	0.92	 = Validation score   (roc_auc)
	38.3s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 542.33s of the 542.32s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/19.8 GB
	0.8927	 = Validation score   (roc_auc)
	3.49s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 538.39s of the 538.39s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/19.7 GB
	0.8917	 = Validation score   (roc_auc)
	3.25s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 534.69s of the 534.69s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.0/19.7 GB
	0.8984	 = Validation score   (roc_auc)
	38.49s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 496.11s of the 496.11s of remaining time.
	Fitting with cpus=2, gpus=1
	0.9218	 = Validation score   (roc_auc)
	0.95s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 495.14s of the 495.14s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.0/19.7 GB
	0.9019	 = Validation score   (roc_auc)
	64.57s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 430.53s of the 430.53s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.1/19.6 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.9193	 = Validation score   (roc_auc)
	4.0s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 426.45s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=4, gpus=1, mem=0.0/19.6 GB
	Ensemble Weights: {'XGBoost': 0.5, 'CatBoost': 0.25, 'LightGBM': 0.2, 'LightGBMLarge': 0.05}
	0.9222	 = Validation score   (roc_auc)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 173.71s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 21678.3 rows/s (2501 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/kaggle/working/adult_gpu_default_q4vvg9pk")

{'dataset': 'adult', 'recipe_name': 'gpu_default', 'score': 0.9316001194450594, 'train_sec': 175.66, 'status': 'ok', 'error': None}

[7/9] elapsed=30.4 min

Warning: path already exists! This predictor may overwrite an existing predictor! path="/kaggle/working/kddcup09_appetency_gpu_default_thbzgxpc"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Sat Jan 17 11:20:45 UTC 2026
CPU Count:          4
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 14.54/14.56 GB | GPU 1: 14.56/14.56 GB
Total GPU Memory:   Free: 29.10 GB, Allocated: 0.03 GB, Total: 29.13 GB
GPU Count:          2
Memory Avail:       19.65 GB / 31.35 GB (62.7%)
Disk Space Avail:   19.50 GB / 19.52 GB (99.9%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/kaggle/working/kddcup09_appetency_gpu_default_thbzgxpc"
Train Data Rows:    40000
Train Data Columns: 230
Label Column:       APPETENCY
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['1', '-1']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = -1
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (1) vs negative (-1) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    20130.64 MB
	Train Data (Original)  Memory Usage: 75.23 MB (0.4% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 6 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 18): ['Var8', 'Var15', 'Var20', 'Var31', 'Var32', 'Var39', 'Var42', 'Var48', 'Var52', 'Var55', 'Var79', 'Var141', 'Var167', 'Var169', 'Var175', 'Var185', 'Var209', 'Var230']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Unused Original Features (Count: 4): ['Var138', 'Var214', 'Var220', 'Var222']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('category', []) : 3 | ['Var214', 'Var220', 'Var222']
		('float', [])    : 1 | ['Var138']
	Types of features in original data (raw dtype, special dtypes):
		('category', []) :  35 | ['Var191', 'Var192', 'Var193', 'Var194', 'Var195', ...]
		('float', [])    : 173 | ['Var1', 'Var2', 'Var3', 'Var4', 'Var5', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  30 | ['Var192', 'Var193', 'Var194', 'Var195', 'Var196', ...]
		('float', [])     : 172 | ['Var1', 'Var2', 'Var3', 'Var4', 'Var5', ...]
		('int', ['bool']) :   6 | ['Var118', 'Var191', 'Var211', 'Var213', 'Var215', ...]
	2.3s = Fit runtime
	208 features in original data used to generate 208 features in processed data.
	Train Data (Processed) Memory Usage: 54.18 MB (0.3% of available memory)
Data preprocessing and feature engineering runtime = 2.41s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0625, Train Rows: 37500, Val Rows: 2500
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 597.59s of the 597.58s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.3/19.5 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
[LightGBM] [Fatal] bin size 3755 cannot run on GPU
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu
	0.8756	 = Validation score   (roc_auc)
	2.39s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 595.16s of the 595.16s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.3/19.5 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
[LightGBM] [Fatal] bin size 3755 cannot run on GPU
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu
	0.8316	 = Validation score   (roc_auc)
	2.39s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 592.75s of the 592.75s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/19.5 GB
	0.8194	 = Validation score   (roc_auc)
	14.03s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 578.55s of the 578.54s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/19.5 GB
	0.8535	 = Validation score   (roc_auc)
	12.07s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 566.30s of the 566.29s of remaining time.
	Fitting with cpus=2, gpus=1
	Training CatBoost with GPU, note that this may negatively impact model quality compared to CPU training.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	0.8634	 = Validation score   (roc_auc)
	31.11s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 535.05s of the 535.05s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/19.5 GB
	0.8159	 = Validation score   (roc_auc)
	6.7s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 528.13s of the 528.13s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.2/19.5 GB
	0.7988	 = Validation score   (roc_auc)
	6.46s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 521.46s of the 521.46s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.5/19.5 GB
No improvement since epoch 2: early stopping
	0.7829	 = Validation score   (roc_auc)
	50.92s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 470.36s of the 470.36s of remaining time.
	Fitting with cpus=2, gpus=1
	0.8767	 = Validation score   (roc_auc)
	2.24s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 468.05s of the 468.05s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.2/19.5 GB
	0.8549	 = Validation score   (roc_auc)
	59.93s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 407.95s of the 407.95s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.5/19.5 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
[LightGBM] [Fatal] bin size 3755 cannot run on GPU
Warning: GPU mode might not be installed for LightGBM, GPU training raised an exception. Falling back to CPU training...Refer to LightGBM GPU documentation: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-versionOne possible method is:	pip uninstall lightgbm -y	pip install lightgbm --install-option=--gpu
	0.8251	 = Validation score   (roc_auc)
	4.57s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 403.34s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=4, gpus=1, mem=0.0/19.5 GB
	Ensemble Weights: {'LightGBMXT': 0.304, 'XGBoost': 0.304, 'RandomForestEntr': 0.217, 'NeuralNetTorch': 0.174}
	0.899	 = Validation score   (roc_auc)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 196.95s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 7040.1 rows/s (2500 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/kaggle/working/kddcup09_appetency_gpu_default_thbzgxpc")

{'dataset': 'kddcup09_appetency', 'recipe_name': 'gpu_default', 'score': 0.859397843410459, 'train_sec': 199.7, 'status': 'ok', 'error': None}

[8/9] elapsed=33.7 min

Warning: path already exists! This predictor may overwrite an existing predictor! path="/kaggle/working/apsfailure_gpu_default_o1__i11t"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Sat Jan 17 11:20:45 UTC 2026
CPU Count:          4
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 14.54/14.56 GB | GPU 1: 14.56/14.56 GB
Total GPU Memory:   Free: 29.10 GB, Allocated: 0.03 GB, Total: 29.13 GB
GPU Count:          2
Memory Avail:       19.52 GB / 31.35 GB (62.3%)
Disk Space Avail:   19.50 GB / 19.52 GB (99.9%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/kaggle/working/apsfailure_gpu_default_o1__i11t"
Train Data Rows:    60800
Train Data Columns: 170
Label Column:       class
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['neg', 'pos']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = pos, class 0 = neg
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (pos) vs negative (neg) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    19993.61 MB
	Train Data (Original)  Memory Usage: 78.86 MB (0.4% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 169 | ['ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000', ...]
		('int', [])   :   1 | ['aa_000']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 168 | ['ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000', ...]
		('int', [])       :   1 | ['aa_000']
		('int', ['bool']) :   1 | ['cd_000']
	0.8s = Fit runtime
	170 features in original data used to generate 170 features in processed data.
	Train Data (Processed) Memory Usage: 78.45 MB (0.4% of available memory)
Data preprocessing and feature engineering runtime = 1.01s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0411, Train Rows: 58301, Val Rows: 2499
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 598.99s of the 598.99s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.5/19.4 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.9946	 = Validation score   (roc_auc)
	4.7s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 594.27s of the 594.27s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.5/19.4 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.9962	 = Validation score   (roc_auc)
	4.97s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 589.28s of the 589.27s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.3/19.4 GB
	0.9935	 = Validation score   (roc_auc)
	89.89s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 499.24s of the 499.24s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.3/19.4 GB
	0.9951	 = Validation score   (roc_auc)
	48.36s	 = Training   runtime
	0.11s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 450.74s of the 450.74s of remaining time.
	Fitting with cpus=2, gpus=1
	Training CatBoost with GPU, note that this may negatively impact model quality compared to CPU training.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	0.9955	 = Validation score   (roc_auc)
	10.72s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 440.00s of the 440.00s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.3/19.4 GB
	0.9934	 = Validation score   (roc_auc)
	8.34s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 431.50s of the 431.50s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.3/19.4 GB
	0.993	 = Validation score   (roc_auc)
	6.77s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 424.57s of the 424.56s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.7/19.4 GB
	0.9868	 = Validation score   (roc_auc)
	51.58s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 372.84s of the 372.84s of remaining time.
	Fitting with cpus=2, gpus=1
	0.9953	 = Validation score   (roc_auc)
	2.43s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 370.38s of the 370.38s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.4/19.4 GB
	0.9928	 = Validation score   (roc_auc)
	55.03s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 315.19s of the 315.19s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.6/19.4 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.994	 = Validation score   (roc_auc)
	11.09s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 304.06s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=4, gpus=1, mem=0.0/19.4 GB
	Ensemble Weights: {'LightGBM': 0.64, 'XGBoost': 0.28, 'NeuralNetFastAI': 0.08}
	0.9963	 = Validation score   (roc_auc)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 296.28s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 21892.4 rows/s (2499 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/kaggle/working/apsfailure_gpu_default_o1__i11t")
Warning: path already exists! This predictor may overwrite an existing predictor! path="/kaggle/working/numerai28.6_gpu_default_j16v3m4l"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Sat Jan 17 11:20:45 UTC 2026
CPU Count:          4
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 14.54/14.56 GB | GPU 1: 14.56/14.56 GB
Total GPU Memory:   Free: 29.10 GB, Allocated: 0.03 GB, Total: 29.13 GB
GPU Count:          2
Memory Avail:       19.64 GB / 31.35 GB (62.6%)
Disk Space Avail:   19.50 GB / 19.52 GB (99.9%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'

{'dataset': 'apsfailure', 'recipe_name': 'gpu_default', 'score': 0.9961735952489721, 'train_sec': 298.76, 'status': 'ok', 'error': None}

[9/9] elapsed=38.7 min

Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/kaggle/working/numerai28.6_gpu_default_j16v3m4l"
Train Data Rows:    77056
Train Data Columns: 21
Label Column:       attribute_21
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['1', '0']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (1) vs negative (0) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    20116.68 MB
	Train Data (Original)  Memory Usage: 12.35 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 21 | ['attribute_0', 'attribute_1', 'attribute_2', 'attribute_3', 'attribute_4', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 21 | ['attribute_0', 'attribute_1', 'attribute_2', 'attribute_3', 'attribute_4', ...]
	0.1s = Fit runtime
	21 features in original data used to generate 21 features in processed data.
	Train Data (Processed) Memory Usage: 12.35 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.2s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0324, Train Rows: 74559, Val Rows: 2497
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 599.80s of the 599.80s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.1/19.6 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.5284	 = Validation score   (roc_auc)
	1.35s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 598.44s of the 598.44s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.1/19.6 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.5232	 = Validation score   (roc_auc)
	1.29s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 597.14s of the 597.14s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.3/19.6 GB
	0.5028	 = Validation score   (roc_auc)
	52.46s	 = Training   runtime
	0.16s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 543.88s of the 543.88s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.3/19.6 GB
	0.506	 = Validation score   (roc_auc)
	67.53s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 475.50s of the 475.50s of remaining time.
	Fitting with cpus=2, gpus=1
	Training CatBoost with GPU, note that this may negatively impact model quality compared to CPU training.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	0.5264	 = Validation score   (roc_auc)
	2.29s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 473.20s of the 473.20s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.3/19.7 GB
	0.5114	 = Validation score   (roc_auc)
	8.68s	 = Training   runtime
	0.14s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 463.60s of the 463.60s of remaining time.
	Fitting with cpus=4, gpus=0, mem=0.3/19.5 GB
	0.5154	 = Validation score   (roc_auc)
	8.66s	 = Training   runtime
	0.14s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 453.92s of the 453.92s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.1/19.5 GB
	0.548	 = Validation score   (roc_auc)
	60.79s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 393.03s of the 393.03s of remaining time.
	Fitting with cpus=2, gpus=1
	0.5129	 = Validation score   (roc_auc)
	0.49s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 392.53s of the 392.52s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.1/19.5 GB
	0.5423	 = Validation score   (roc_auc)
	41.45s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 351.06s of the 351.06s of remaining time.
	Fitting with cpus=2, gpus=1, mem=0.1/19.5 GB
	Warning: Training LightGBM with GPU. This may negatively impact model quality compared to CPU training.
	0.4891	 = Validation score   (roc_auc)
	1.53s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 349.52s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=4, gpus=1, mem=0.0/19.5 GB
	Ensemble Weights: {'NeuralNetFastAI': 0.625, 'NeuralNetTorch': 0.375}
	0.5502	 = Validation score   (roc_auc)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 250.67s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 69427.8 rows/s (2497 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/kaggle/working/numerai28.6_gpu_default_j16v3m4l")

{'dataset': 'numerai28.6', 'recipe_name': 'gpu_default', 'score': 0.522821466325643, 'train_sec': 252.54, 'status': 'ok', 'error': None}

Done. Total elapsed: 42.9 min
saved to: /kaggle/working/autogluon_openml_results/openml_gpu_default_results.csv
rows: 9

,task_order,dataset,openml_id,metric,recipe_name,score,train_sec,best_model,trained_models,status,error
4,14,bank-marketing,14965,roc_auc,gpu_default,0.936927,167.88,WeightedEnsemble_L2,12,ok,None
5,15,adult,7592,roc_auc,gpu_default,0.931600,175.66,WeightedEnsemble_L2,12,ok,None
6,16,kddcup09_appetency,3945,roc_auc,gpu_default,0.859398,199.70,WeightedEnsemble_L2,12,ok,None
7,17,apsfailure,168868,roc_auc,gpu_default,0.996174,298.76,WeightedEnsemble_L2,12,ok,None
8,18,numerai28.6,167120,roc_auc,gpu_default,0.522821,252.54,WeightedEnsemble_L2,12,ok,None

## 6. Known Issues

| 이슈 | 원인 | 정리 |
| --- | --- | --- |
| 평가 프로토콜 차이 | 이번 노트북은 `train 80% / test 20%` holdout을 사용함 | 논문/OpenML 공식 fold 점수와 직접 비교가 아니라 기준 결과로 해석 |
| GPU를 켜도 일부 단계는 CPU로 실행될 수 있음 | AutoGluon Tabular 기본 탐색 공간이 CPU/GPU 혼합 모델군이기 때문 | `gpu_default`를 GPU 활성화 대표 설정으로 해석 |
| GPU 2개를 항상 꽉 채워 쓰기 어려움 | Tabular fit이 사실상 순차적으로 진행되고 개별 모델도 대개 1개 GPU를 사용함 | 이번 발표는 비교 단순화를 위해 `num_gpus=1` 기준으로 설명 |

실제 실행 중 발생한 실패는 아래 결과 요약 셀에서 별도로 자동 표시합니다.

## 7. Result Interpretation

이 구간은 실험 결과를 다시 정리하는 셀입니다.

자동으로 나오는 내용:
- raw result table
- task별 결과 표
- 평균 점수와 평균 학습 시간
- 실제 실패 유형 분류
- 한글 요약 문단

In [17]:
import numpy as np
import pandas as pd
from IPython.display import Markdown, display

def classify_issue(error_text):
    if pd.isna(error_text) or not str(error_text).strip():
        return None
    text = str(error_text).lower()
    if 'bin size' in text and 'gpu' in text:
        return 'LightGBM GPU 제한'
    if 'cuda' in text or 'gpu' in text:
        return 'GPU 설정/호환 이슈'
    if 'out of memory' in text or 'memoryerror' in text or 'std::bad_alloc' in text:
        return '메모리 부족'
    if 'roc auc' in text or 'probability columns' in text or 'log_loss' in text:
        return '평가 지표/라벨 이슈'
    if 'openml' in text or 'http' in text or 'connection' in text or 'download' in text:
        return '데이터 다운로드/네트워크 이슈'
    return '기타 실행 이슈'

if not RESULTS_CSV.exists():
    print('results.csv 가 아직 없습니다. 실행 셀 로그를 확인하세요.')
else:
    results_df = pd.read_csv(RESULTS_CSV).sort_values(['task_order', 'recipe_name']).reset_index(drop=True)
    results_df['error'] = results_df['error'].fillna('').astype(str).str.strip()
    results_df['issue_type'] = results_df['error'].apply(classify_issue)

    recipe_meta_df = pd.DataFrame(active_recipes)[['recipe_name', 'description', 'num_gpus']]
    recipe_meta_df = recipe_meta_df.rename(columns={'description': 'recipe_description'})
    results_df = results_df.drop(columns=['recipe_description', 'num_gpus'], errors='ignore')
    results_df = results_df.merge(recipe_meta_df, on='recipe_name', how='left')

    print('Raw experiment results')
    display_cols = [
        'task_order',
        'dataset',
        'recipe_name',
        'recipe_description',
        'score',
        'train_sec',
        'best_model',
        'trained_models',
        'status',
        'issue_type',
        'error',
    ]
    display(results_df[[c for c in display_cols if c in results_df.columns]])

    failure_df = results_df[results_df['status'] != 'ok'].copy()
    ok_df = results_df[results_df['status'] == 'ok'].copy()

    if ok_df.empty:
        print('성공한 실행이 아직 없습니다.')
        recipe_summary = pd.DataFrame()
        score_pivot = pd.DataFrame()
    else:
        score_pivot = ok_df.pivot_table(index='dataset', columns='recipe_name', values='score')
        time_pivot = ok_df.pivot_table(index='dataset', columns='recipe_name', values='train_sec')

        recipe_summary = results_df.groupby(['recipe_name', 'recipe_description'], as_index=False).agg(
            planned_runs=('dataset', 'size'),
            success_runs=('status', lambda s: int((s == 'ok').sum())),
            failed_runs=('status', lambda s: int((s != 'ok').sum())),
            mean_score=('score', 'mean'),
            median_score=('score', 'median'),
            mean_train_sec=('train_sec', 'mean'),
            median_train_sec=('train_sec', 'median'),
            mean_trained_models=('trained_models', 'mean'),
        )
        recipe_summary['success_rate'] = (recipe_summary['success_runs'] / recipe_summary['planned_runs']).round(3)
        recipe_summary = recipe_summary.sort_values(['mean_score'], ascending=[False], na_position='last').reset_index(drop=True)

        print('Recipe summary for presentation')
        display(recipe_summary)

        print('Score pivot')
        display(score_pivot)

    if failure_df.empty:
        print('Observed failures: none')
    else:
        print('Observed failures')
        display(failure_df[['task_order', 'dataset', 'recipe_name', 'issue_type', 'error']])

    presentation_lines = [
        '## Presentation Draft',
        '- 이번 실험은 OpenML 9개 태스크를 Kaggle T4, 600초, train 80% / test 20% 조건에서 실행한 결과입니다.',
        '- 이번 노트북은 AutoGluon 내부 recipe 비교 대신 `gpu_default` 설정 하나를 기준 결과로 사용합니다.',
    ]

    if ok_df.empty:
        presentation_lines.append('- 아직 성공한 실행이 없어서 먼저 실행 셀을 완료한 뒤 요약을 확인해야 합니다.')
    else:
        best_score_row = recipe_summary.dropna(subset=['mean_score']).iloc[0]
        presentation_lines.append(
            f"- 평균 점수 기준으로는 `{best_score_row['recipe_name']}`가 가장 높았고, 평균 점수는 {best_score_row['mean_score']:.4f}였습니다."
        )

        fastest_row = recipe_summary.dropna(subset=['mean_train_sec']).sort_values('mean_train_sec').iloc[0]
        presentation_lines.append(
            f"- 시간 기준으로는 `{fastest_row['recipe_name']}`가 평균 {fastest_row['mean_train_sec']:.1f}초로 가장 빨랐습니다."
        )

    if failure_df.empty:
        presentation_lines.append('- 이번 실행에서는 치명적인 실패 없이 기준 결과를 확보할 수 있었습니다.')
    else:
        top_issue_label = failure_df['issue_type'].fillna('기타 실행 이슈').value_counts().index[0]
        presentation_lines.append(
            f"- 실패는 총 {len(failure_df)}건 있었고, 가장 많이 관찰된 문제 유형은 `{top_issue_label}`였습니다."
        )

    presentation_lines.append('- 이 결과는 다른 모델과 비교할 때 AutoGluon GPU 기본 설정의 기준 점수로 사용할 수 있습니다.')
    presentation_lines.append('- 또 GPU를 켠다고 모든 단계가 GPU로 도는 것은 아니므로, 로그와 실패 유형을 함께 확인하는 것이 중요합니다.')

    display(Markdown('\n'.join(presentation_lines)))

Raw experiment results

,task_order,dataset,recipe_name,recipe_description,score,train_sec,best_model,trained_models,status,issue_type,error
0,10,guillermo,gpu_default,"GPU enabled, default search space",0.905757,611.62,WeightedEnsemble_L2,8,ok,None,
1,11,riccardo,gpu_default,"GPU enabled, default search space",0.999734,605.26,WeightedEnsemble_L2,5,ok,None,
2,12,amazon_employee,gpu_default,"GPU enabled, default search space",0.883654,96.66,WeightedEnsemble_L2,12,ok,None,
3,13,nomao,gpu_default,"GPU enabled, default search space",0.996191,165.55,WeightedEnsemble_L2,12,ok,None,
4,14,bank-marketing,gpu_default,"GPU enabled, default search space",0.936927,167.88,WeightedEnsemble_L2,12,ok,None,
5,15,adult,gpu_default,"GPU enabled, default search space",0.931600,175.66,WeightedEnsemble_L2,12,ok,None,
6,16,kddcup09_appetency,gpu_default,"GPU enabled, default search space",0.859398,199.70,WeightedEnsemble_L2,12,ok,None,
7,17,apsfailure,gpu_default,"GPU enabled, default search space",0.996174,298.76,WeightedEnsemble_L2,12,ok,None,
8,18,numerai28.6,gpu_default,"GPU enabled, default search space",0.522821,252.54,WeightedEnsemble_L2,12,ok,None,

Recipe summary for presentation

,recipe_name,recipe_description,planned_runs,success_runs,failed_runs,mean_score,median_score,mean_train_sec,median_train_sec,mean_trained_models,success_rate
0,gpu_default,"GPU enabled, default search space",9,9,0,0.892473,0.9316,285.958889,199.7,10.777778,1.0

Score pivot

recipe_name         gpu_default
dataset
adult                  0.931600
amazon_employee        0.883654
apsfailure             0.996174
bank-marketing         0.936927
guillermo              0.905757
kddcup09_appetency     0.859398
nomao                  0.996191
numerai28.6            0.522821
riccardo               0.999734

Observed failures: none

## Presentation Draft
- 이번 실험은 OpenML 9개 태스크를 Kaggle T4, 600초, train 80% / test 20% 조건에서 실행한 결과입니다.
- 이번 노트북은 AutoGluon 내부 recipe 비교 대신 `gpu_default` 설정 하나를 기준 결과로 사용합니다.
- 평균 점수 기준으로는 `gpu_default`가 가장 높았고, 평균 점수는 0.8925였습니다.
- 시간 기준으로는 `gpu_default`가 평균 286.0초로 가장 빨랐습니다.
- 이번 실행에서는 치명적인 실패 없이 기준 결과를 확보할 수 있었습니다.
- 이 결과는 다른 모델과 비교할 때 AutoGluon GPU 기본 설정의 기준 점수로 사용할 수 있습니다.
- 또 GPU를 켠다고 모든 단계가 GPU로 도는 것은 아니므로, 로그와 실패 유형을 함께 확인하는 것이 중요합니다.